/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CategoryChart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useClientOnlyValue.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionFilter`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FilterModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/NewTransactionModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transacoes` | `/transacoes`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CategoryChart`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TransactionList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/useClientOnlyValue.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/useClientOnlyValue`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TransactionFilter`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/FilterModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/NewTransactionModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transacoes` | `/transacoes`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../components/CategoryChart${`?${string}` | `#${string}` | ''}` | `/../components/TransactionList${`?${string}` | `#${string}` | ''}` | `/../components/useClientOnlyValue.web${`?${string}` | `#${string}` | ''}` | `/../components/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../components/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../components/useClientOnlyValue${`?${string}` | `#${string}` | ''}` | `/../components/TransactionFilter${`?${string}` | `#${string}` | ''}` | `/../components/FilterModal${`?${string}` | `#${string}` | ''}` | `/../components/NewTransactionModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transacoes${`?${string}` | `#${string}` | ''}` | `/transacoes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CategoryChart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useClientOnlyValue.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/useClientOnlyValue`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TransactionFilter`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FilterModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/NewTransactionModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transacoes` | `/transacoes`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
